modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="${mod_issues}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_url}"
logoFile="${mod_logo}"
credits="${mod_credits}"
authors="${mod_credits}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[mixins]]
    config = "${mod_id}.mixins.json"
[[mixins]]
    config = "${mod_id}.forge.mixins.json"